on:
  # issues:
  # issue_comment:
  # pull_request_target:
  workflow_dispatch:

jobs:
  get-pwned:
    runs-on: ubuntu-latest
    steps:
      - name: Log event and get pwned
        run: echo '${{ tojson (github) }}' | jq
